export const LOAD_GROUPS_PAGING_REQUEST = "LOAD_GROUPS_PAGING_REQUEST";
export const LOAD_GROUPS_PAGING_SUCCESS = "LOAD_GROUPS_PAGING_SUCCESS";
export const LOAD_GROUPS_PAGING_FAILURE = "LOAD_GROUPS_PAGING_FAILURE";

export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";

export const GET_GROUP_BY_ID_REQUEST = "GET_GROUP_BY_ID_REQUEST";
export const GET_GROUP_BY_ID_SUCCESS = "GET_GROUP_BY_ID_SUCCESS";
export const GET_GROUP_BY_ID_FAILURE = "GET_GROUP_BY_ID_FAILURE";

export const UPDATE_GROUP_REQUEST = "UPDATE_GROUP_REQUEST";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_FAILURE = "UPDATE_GROUP_FAILURE";

export const DELETE_GROUPS_REQUEST = "DELETE_GROUPS_REQUEST";
export const DELETE_GROUPS_SUCCESS = "DELETE_GROUPS_SUCCESS";
export const DELETE_GROUPS_FAILURE = "DELETE_GROUPS_FAILURE";

export const DOWNLOAD_FILE_REQUEST = "DOWNLOAD_FILE_REQUEST";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_FAILURE = "DOWNLOAD_FILE_FAILURE";

export const DELETE_FILE_REQUEST = "DELETE_FILE_REQUEST";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAILURE = "DELETE_FILE_FAILURE";

export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

export const DELETE_MEMBERS_REQUEST = "DELETE_MEMBERS_REQUEST";
export const DELETE_MEMBERS_SUCCESS = "DELETE_MEMBERS_SUCCESS";
export const DELETE_MEMBERS_FAILURE = "DELETE_MEMBERS_FAILURE";
