export const LOAD_TEACHERS_PAGING_REQUEST = "LOAD_TEACHERS_PAGING_REQUEST";
export const LOAD_TEACHERS_PAGING_SUCCESS = "LOAD_TEACHERS_PAGING_SUCCESS";
export const LOAD_TEACHERS_PAGING_FAILURE = "LOAD_TEACHERS_PAGING_FAILURE";

export const ADD_TEACHER_REQUEST = "ADD_TEACHER_REQUEST";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAILURE = "ADD_TEACHER_FAILURE";

export const GET_TEACHER_BY_ID_REQUEST = "GET_TEACHER_BY_ID_REQUEST";
export const GET_TEACHER_BY_ID_SUCCESS = "GET_TEACHER_BY_ID_SUCCESS";
export const GET_TEACHER_BY_ID_FAILURE = "GET_TEACHER_BY_ID_FAILURE";

export const UPDATE_TEACHER_REQUEST = "UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAILURE = "UPDATE_TEACHER_FAILURE";

export const DELETE_TEACHERS_REQUEST = "DELETE_TEACHERS_REQUEST";
export const DELETE_TEACHERS_SUCCESS = "DELETE_TEACHERS_SUCCESS";
export const DELETE_TEACHERS_FAILURE = "DELETE_TEACHERS_FAILURE";
