export const LOAD_STUDENTS_PAGING_REQUEST = "LOAD_STUDENTS_PAGING_REQUEST";
export const LOAD_STUDENTS_PAGING_SUCCESS = "LOAD_STUDENTS_PAGING_SUCCESS";
export const LOAD_STUDENTS_PAGING_FAILURE = "LOAD_STUDENTS_PAGING_FAILURE";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAILURE = "ADD_STUDENT_FAILURE";

export const GET_STUDENT_BY_ID_REQUEST = "GET_STUDENT_BY_ID_REQUEST";
export const GET_STUDENT_BY_ID_SUCCESS = "GET_STUDENT_BY_ID_SUCCESS";
export const GET_STUDENT_BY_ID_FAILURE = "GET_STUDENT_BY_ID_FAILURE";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE";

export const DELETE_STUDENTS_REQUEST = "DELETE_STUDENTS_REQUEST";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_FAILURE = "DELETE_STUDENTS_FAILURE";
