export const INVITE_REQUEST = "INVITE_REQUEST";
export const INVITE_SUCCESS = "INVITE_SUCCESS";
export const INVITE_FAILURE = "INVITE_FAILURE";

export const RECEIVED_INVITE_REQUEST = "RECEIVED_INVITE_REQUEST";
export const RECEIVED_INVITE_SUCCESS = "RECEIVED_INVITE_SUCCESS";
export const RECEIVED_INVITE_FAILURE = "RECEIVED_INVITE_FAILURE";

export const SENT_INVITE_REQUEST = "SENT_INVITE_REQUEST";
export const SENT_INVITE_SUCCESS = "SENT_INVITE_SUCCESS";
export const SENT_INVITE_FAILURE = "SENT_INVITE_FAILURE";

export const ADD_RECEIVED_INVITE = "ADD_RECEIVED_INVITE";

export const MARK_READ_REQUEST = "MARK_READ_REQUEST";
export const MARK_READ_SUCCESS = "MARK_READ_SUCCESS";
export const MARK_READ_FAILURE = "MARK_READ_FAILURE";

export const ACCEPT_INVITE_REQUEST = "ACCEPT_INVITE_REQUEST";
export const ACCEPT_INVITE_SUCCESS = "ACCEPT_INVITE_SUCCESS";
export const ACCEPT_INVITE_FAILURE = "ACCEPT_INVITE_FAILURE";

export const REMOVE_INVITE_REQUEST = "REMOVE_INVITE_REQUEST";
export const REMOVE_INVITE_SUCCESS = "REMOVE_INVITE_SUCCESS";
export const REMOVE_INVITE_FAILURE = "REMOVE_INVITE_FAILURE";

export const REMOVE_RECEIVED_INVITE = "REMOVE_RECEIVED_INVITE";
export const REMOVE_SENT_INVITE = "REMOVE_SENT_INVITE";
